apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: field-web, namespace: argocd }
spec:
  project: default
  source: { repoURL: "https://github.com/beladjioo/Spectra.git", targetRevision: main, path: apps/web }
  destination: { server: "https://kubernetes.default.svc", namespace: spectra }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
