apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spectra
configMapGenerator:
  - name: spectra-dashboards
    files:
      - ism-health.json=dashboards/ism-health.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
