// Banque de questions type examen radioamateur français (ANFR).
// Deux domaines comme à l'examen : réglementation et technique.
// Chaque question référence si utile une note de la bibliothèque.

export type Category = "reglementation" | "technique";

export type Question = {
  id: string;
  cat: Category;
  q: string;
  choices: [string, string, string, string];
  answer: 0 | 1 | 2 | 3;
  why: string;
  note?: string; // slug d'une note de la bibliothèque pour réviser
};

export const CATEGORY_LABEL: Record<Category, string> = {
  reglementation: "Réglementation",
  technique: "Technique",
};

export const QUESTIONS: Question[] = [
  // ── Réglementation ────────────────────────────────────────────────────────
  {
    id: "r-anfr",
    cat: "reglementation",
    q: "En France, quel organisme organise l'examen et délivre le certificat d'opérateur radioamateur ?",
    choices: ["L'ANFR", "L'ARCEP", "La DGAC", "L'ARCOM"],
    answer: 0,
    why: "L'ANFR (Agence nationale des fréquences) organise l'examen, délivre le certificat et attribue les indicatifs.",
    note: "examen-radioamateur",
  },
  {
    id: "r-qth",
    cat: "reglementation",
    q: "Que signifie le code Q « QTH » ?",
    choices: ["Ma position est…", "Je change de fréquence", "Qui m'appelle ?", "Accusé de réception"],
    answer: 0,
    why: "QTH = position/emplacement de la station. « Mon QTH est Montpellier. »",
    note: "code-q-phonetique-rst",
  },
  {
    id: "r-qrm",
    cat: "reglementation",
    q: "Un opérateur signale du « QRM ». De quoi parle-t-il ?",
    choices: [
      "De brouillages d'origine artificielle",
      "De parasites atmosphériques",
      "D'un signal trop fort",
      "D'une demande de relais",
    ],
    answer: 0,
    why: "QRM = interférences artificielles (autres émissions). Les parasites naturels, c'est QRN.",
    note: "code-q-phonetique-rst",
  },
  {
    id: "r-qsy",
    cat: "reglementation",
    q: "Que signifie « QSY » ?",
    choices: ["Je change de fréquence", "Je diminue la puissance", "Je termine le contact", "Je répète le message"],
    answer: 0,
    why: "QSY = changer de fréquence d'émission. « On QSY sur 145,450 MHz. »",
    note: "code-q-phonetique-rst",
  },
  {
    id: "r-qsl",
    cat: "reglementation",
    q: "Une « carte QSL » sert à :",
    choices: [
      "Confirmer un contact radio",
      "Déclarer son antenne",
      "Demander une licence",
      "Signaler un brouillage",
    ],
    answer: 0,
    why: "QSL = accusé de réception : la carte (papier ou électronique) confirme qu'un QSO a bien eu lieu.",
    note: "indicatifs-trafic-journal",
  },
  {
    id: "r-qrz",
    cat: "reglementation",
    q: "Que demande un opérateur qui lance « QRZ ? » ?",
    choices: ["Qui m'appelle ?", "Quelle est ma force de signal ?", "Êtes-vous prêt ?", "Quelle heure est-il ?"],
    answer: 0,
    why: "QRZ ? = « qui m'appelle ? » — typiquement après un appel entendu partiellement.",
    note: "code-q-phonetique-rst",
  },
  {
    id: "r-phon-r",
    cat: "reglementation",
    q: "Dans l'alphabet phonétique international, la lettre R s'épelle :",
    choices: ["Romeo", "Radio", "Roger", "Rome"],
    answer: 0,
    why: "A = Alfa, B = Bravo… R = Romeo. « Roger » signifie « bien reçu », ce n'est pas une lettre.",
    note: "code-q-phonetique-rst",
  },
  {
    id: "r-prefixe",
    cat: "reglementation",
    q: "L'indicatif F4ABC commence par F. Que signifie ce préfixe ?",
    choices: [
      "La station est française",
      "L'opérateur est de classe F",
      "La station est fixe",
      "L'opérateur utilise la FM",
    ],
    answer: 0,
    why: "Le préfixe identifie le pays d'attribution : F (et TM, TK…) = France.",
    note: "indicatifs-trafic-journal",
  },
  {
    id: "r-2m",
    cat: "reglementation",
    q: "En France, la bande radioamateur « 2 mètres » s'étend de :",
    choices: ["144 à 146 MHz", "144 à 148 MHz", "140 à 144 MHz", "146 à 148 MHz"],
    answer: 0,
    why: "En région 1 de l'UIT (Europe), le 2 m radioamateur va de 144 à 146 MHz.",
    note: "bandes-radioamateur",
  },
  {
    id: "r-70cm",
    cat: "reglementation",
    q: "La bande « 70 centimètres » correspond à :",
    choices: ["430–440 MHz", "420–450 MHz", "400–410 MHz", "440–460 MHz"],
    answer: 0,
    why: "En France, le 70 cm s'étend de 430 à 440 MHz (statut partagé).",
    note: "bandes-radioamateur",
  },
  {
    id: "r-40m",
    cat: "reglementation",
    q: "La bande des 40 mètres s'étend en France de :",
    choices: ["7,0 à 7,2 MHz", "7,0 à 7,5 MHz", "6,9 à 7,1 MHz", "7,2 à 7,4 MHz"],
    answer: 0,
    why: "Le 40 m : 7,0–7,2 MHz en région 1 — une bande HF très active le soir.",
    note: "bandes-radioamateur",
  },
  {
    id: "r-f3e",
    cat: "reglementation",
    q: "La classe d'émission F3E désigne :",
    choices: [
      "La téléphonie en modulation de fréquence",
      "La télégraphie Morse",
      "La téléphonie en bande latérale unique",
      "La télévision amateur",
    ],
    answer: 0,
    why: "F = modulation de fréquence, 3 = un canal analogique, E = téléphonie. F3E = la phonie FM classique.",
    note: "modulations",
  },
  {
    id: "r-a3e",
    cat: "reglementation",
    q: "La classe d'émission A3E correspond à :",
    choices: [
      "La téléphonie en modulation d'amplitude",
      "La téléphonie FM",
      "La télégraphie",
      "Les données numériques",
    ],
    answer: 0,
    why: "A = modulation d'amplitude double bande, 3 = analogique, E = téléphonie. C'est l'AM « historique ».",
    note: "modulations",
  },
  {
    id: "r-j3e",
    cat: "reglementation",
    q: "La BLU (bande latérale unique) en téléphonie correspond à la classe :",
    choices: ["J3E", "F3E", "A1A", "G3E"],
    answer: 0,
    why: "J3E = BLU à porteuse supprimée, le mode phonie dominant en HF (USB/LSB).",
    note: "modulations",
  },
  {
    id: "r-rst59",
    cat: "reglementation",
    q: "Un report « 59 » signifie :",
    choices: [
      "Parfaitement lisible et signal très fort",
      "Faiblement lisible, signal fort",
      "Lisible, signal faible",
      "Code postal du correspondant",
    ],
    answer: 0,
    why: "RST : R5 = parfaitement lisible (sur 5), S9 = signal très fort (sur 9).",
    note: "code-q-phonetique-rst",
  },
  {
    id: "r-secret",
    cat: "reglementation",
    q: "Vous captez une communication qui ne vous est pas destinée. Que dit la loi ?",
    choices: [
      "Interdiction de la divulguer ou de l'exploiter",
      "Vous pouvez la publier si elle est intéressante",
      "Vous devez la signaler à l'ANFR",
      "Vous pouvez y répondre",
    ],
    answer: 0,
    why: "Le secret des correspondances s'applique : écouter n'autorise jamais à divulguer le contenu à des tiers.",
    note: "legal-securite",
  },
  {
    id: "r-clair",
    cat: "reglementation",
    q: "Les communications radioamateurs doivent se faire :",
    choices: [
      "En langage clair, sans chiffrement destiné à masquer le sens",
      "Dans une langue européenne uniquement",
      "En code secret entre membres d'un club",
      "Uniquement en Morse sur HF",
    ],
    answer: 0,
    why: "Le service amateur impose le langage clair : pas de chiffrement pour dissimuler le contenu des échanges.",
    note: "reglementation",
  },
  {
    id: "r-musique",
    cat: "reglementation",
    q: "Diffuser de la musique ou de la publicité sur les bandes amateurs est :",
    choices: ["Interdit", "Toléré le week-end", "Autorisé en FM seulement", "Autorisé en dessous de 30 MHz"],
    answer: 0,
    why: "Les bandes amateurs servent à l'expérimentation et au trafic entre stations autorisées — pas de radiodiffusion.",
    note: "reglementation",
  },
  {
    id: "r-indicatif",
    cat: "reglementation",
    q: "Quand devez-vous transmettre votre indicatif en cours de contact ?",
    choices: [
      "Au début, à la fin et à intervalles réguliers",
      "Uniquement au début",
      "Uniquement si on vous le demande",
      "Jamais en FM",
    ],
    answer: 0,
    why: "L'identification est obligatoire en début et fin d'émission et à intervalles rapprochés pendant le trafic.",
    note: "indicatifs-trafic-journal",
  },
  {
    id: "r-exam",
    cat: "reglementation",
    q: "L'examen radioamateur français évalue :",
    choices: [
      "La réglementation et la technique",
      "Uniquement le code Morse",
      "Uniquement la technique",
      "L'anglais aéronautique",
    ],
    answer: 0,
    why: "Deux épreuves : réglementation (et procédures) + technique (électricité/radioélectricité). Le Morse n'est plus exigé.",
    note: "examen-radioamateur",
  },

  // ── Technique ─────────────────────────────────────────────────────────────
  {
    id: "t-ohm",
    cat: "technique",
    q: "Une résistance de 50 Ω est parcourue par 0,1 A. La tension à ses bornes vaut :",
    choices: ["5 V", "0,5 V", "50 V", "500 V"],
    answer: 0,
    why: "Loi d'Ohm : U = R × I = 50 × 0,1 = 5 V.",
    note: "electricite",
  },
  {
    id: "t-puissance",
    cat: "technique",
    q: "Un émetteur alimenté en 13,8 V consomme 2 A. La puissance consommée est d'environ :",
    choices: ["27,6 W", "6,9 W", "15,8 W", "55,2 W"],
    answer: 0,
    why: "P = U × I = 13,8 × 2 = 27,6 W.",
    note: "electricite",
  },
  {
    id: "t-3db",
    cat: "technique",
    q: "Augmenter une puissance de 3 dB revient à la :",
    choices: ["Doubler", "Tripler", "Multiplier par 10", "Augmenter de 3 %"],
    answer: 0,
    why: "+3 dB ≈ ×2 en puissance ; +10 dB = ×10 ; +20 dB = ×100. Le décibel est logarithmique.",
    note: "decibels",
  },
  {
    id: "t-20db",
    cat: "technique",
    q: "+20 dB correspond à une multiplication de la puissance par :",
    choices: ["100", "20", "2", "1000"],
    answer: 0,
    why: "20 dB = 2 × 10 dB = ×10 × ×10 = ×100.",
    note: "decibels",
  },
  {
    id: "t-lambda144",
    cat: "technique",
    q: "Quelle est la longueur d'onde d'un signal à 144 MHz ?",
    choices: ["Environ 2 m", "Environ 4 m", "Environ 70 cm", "Environ 1 m"],
    answer: 0,
    why: "λ(m) = 300 / f(MHz) = 300/144 ≈ 2,08 m — d'où le nom « bande des 2 mètres ».",
    note: "ondes-radio",
  },
  {
    id: "t-freq10m",
    cat: "technique",
    q: "Une longueur d'onde de 10 m correspond à une fréquence de :",
    choices: ["30 MHz", "10 MHz", "3 MHz", "300 MHz"],
    answer: 0,
    why: "f(MHz) = 300 / λ(m) = 300/10 = 30 MHz.",
    note: "ondes-radio",
  },
  {
    id: "t-dipole",
    cat: "technique",
    q: "Un dipôle demi-onde pour 100 MHz mesure environ :",
    choices: ["1,5 m", "3 m", "0,75 m", "6 m"],
    answer: 0,
    why: "λ = 300/100 = 3 m ; un dipôle demi-onde fait λ/2 ≈ 1,5 m.",
    note: "antennes",
  },
  {
    id: "t-coax",
    cat: "technique",
    q: "L'impédance caractéristique des câbles coaxiaux usuels en radio est :",
    choices: ["50 Ω", "75 Ω", "300 Ω", "600 Ω"],
    answer: 0,
    why: "Le standard radio/SDR est 50 Ω (la télévision utilise du 75 Ω).",
    note: "lignes-ros-adaptation",
  },
  {
    id: "t-ros",
    cat: "technique",
    q: "Le ROS idéal d'une antenne parfaitement adaptée vaut :",
    choices: ["1:1", "0:1", "2:1", "∞"],
    answer: 0,
    why: "ROS 1:1 = toute la puissance part dans l'antenne, aucune onde réfléchie.",
    note: "lignes-ros-adaptation",
  },
  {
    id: "t-ros-eleve",
    cat: "technique",
    q: "Un ROS élevé indique :",
    choices: [
      "Une désadaptation entre la ligne et l'antenne",
      "Une antenne trop performante",
      "Un récepteur trop sensible",
      "Une propagation exceptionnelle",
    ],
    answer: 0,
    why: "Plus le ROS monte, plus la puissance est réfléchie vers l'émetteur au lieu d'être rayonnée.",
    note: "lignes-ros-adaptation",
  },
  {
    id: "t-passebas",
    cat: "technique",
    q: "En sortie d'émetteur, un filtre passe-bas sert à :",
    choices: [
      "Atténuer les harmoniques au-dessus de la fréquence de travail",
      "Amplifier les basses fréquences",
      "Supprimer le bruit de fond",
      "Adapter l'impédance",
    ],
    answer: 0,
    why: "Il laisse passer la fondamentale et atténue les harmoniques (2f, 3f…) qui brouilleraient d'autres services.",
    note: "circuits-resonance-filtres",
  },
  {
    id: "t-harmonique",
    cat: "technique",
    q: "Le deuxième harmonique d'un émetteur réglé sur 7 MHz se trouve à :",
    choices: ["14 MHz", "3,5 MHz", "21 MHz", "7,2 MHz"],
    answer: 0,
    why: "Harmonique 2 = 2 × f = 14 MHz — en plein dans la bande des 20 m, d'où l'importance du filtrage.",
    note: "circuits-resonance-filtres",
  },
  {
    id: "t-condo",
    cat: "technique",
    q: "Un condensateur :",
    choices: [
      "Bloque le courant continu et laisse passer l'alternatif",
      "Laisse passer le continu et bloque l'alternatif",
      "Amplifie le signal",
      "Redresse le courant",
    ],
    answer: 0,
    why: "Le condensateur se charge en continu (courant nul en régime établi) mais transmet les variations.",
    note: "composants-electroniques",
  },
  {
    id: "t-diode",
    cat: "technique",
    q: "Une diode laisse passer le courant :",
    choices: ["Dans un seul sens", "Dans les deux sens", "Jamais", "Seulement en alternatif"],
    answer: 0,
    why: "Conduction de l'anode vers la cathode en polarisation directe — c'est la base du redressement et de la détection AM.",
    note: "composants-electroniques",
  },
  {
    id: "t-lc",
    cat: "technique",
    q: "Dans un circuit LC, si on diminue la capacité C, la fréquence de résonance :",
    choices: ["Augmente", "Diminue", "Ne change pas", "Devient nulle"],
    answer: 0,
    why: "f = 1/(2π√(LC)) : C plus petit → √(LC) plus petit → f plus grande.",
    note: "circuits-resonance-filtres",
  },
  {
    id: "t-iono",
    cat: "technique",
    q: "Les liaisons HF intercontinentales (ex. 14 MHz) sont possibles grâce à :",
    choices: [
      "La réflexion sur l'ionosphère",
      "La courbure des ondes par le vent",
      "Les satellites",
      "La conduction par le sol uniquement",
    ],
    answer: 0,
    why: "Les couches ionisées (notamment F) réfléchissent les ondes courtes, permettant des bonds de milliers de km.",
    note: "propagation",
  },
  {
    id: "t-vhf",
    cat: "technique",
    q: "En VHF/UHF, la propagation habituelle se fait :",
    choices: [
      "En ligne de vue (portée quasi optique)",
      "Par réflexion ionosphérique systématique",
      "Par le sol sur des milliers de km",
      "Uniquement la nuit",
    ],
    answer: 0,
    why: "Au-dessus de ~30 MHz, l'ionosphère ne réfléchit plus de façon fiable : la portée est essentiellement directe.",
    note: "propagation",
  },
  {
    id: "t-fm",
    cat: "technique",
    q: "En modulation de fréquence (FM), l'information fait varier :",
    choices: [
      "La fréquence instantanée de la porteuse",
      "L'amplitude de la porteuse",
      "La phase uniquement",
      "La largeur des impulsions",
    ],
    answer: 0,
    why: "FM = la fréquence s'écarte de la porteuse au rythme du signal modulant ; l'amplitude reste constante.",
    note: "modulations",
  },
  {
    id: "t-snr",
    cat: "technique",
    q: "Un signal 20 dB au-dessus du bruit a une puissance :",
    choices: ["100 fois celle du bruit", "20 fois celle du bruit", "2 fois celle du bruit", "400 fois celle du bruit"],
    answer: 0,
    why: "SNR de 20 dB = rapport de puissance 10^(20/10) = 100.",
    note: "bruit-et-snr",
  },
  {
    id: "t-dbm",
    cat: "technique",
    q: "+30 dBm correspond à une puissance de :",
    choices: ["1 W", "30 W", "100 mW", "3 W"],
    answer: 0,
    why: "0 dBm = 1 mW ; +30 dB = ×1000 → 1 W.",
    note: "decibels",
  },
];

// Mélange déterministe côté appelant ; ici juste les utilitaires.
export const byCategory = (cat: Category) => QUESTIONS.filter((q) => q.cat === cat);

export function shuffled<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
